### ISSUE TITLE
feature: rspack & turbopack

### ISSUE THREAD

**Issue by tamusjroyce** [remix-run/remix-webpack-demo#10]
rspack was recently released. Is there any advantages to using rspack over remix compiler? Now that rspack might replace webpack with subseconds?

feature request might be to support rspack. But it no advantages, please close this after replying.

**Comment by pcattori** [comment]
This demo is designed for helping migrate existing/legacy/brownfield apps from Webpack to Remix. Since rspack emerged _after_ Remix already existed, support for rspack is out-of-scope for this repo.
