### ISSUE TITLE
every save logs a not found object

### ISSUE THREAD

**Issue by ryanflorence** [remix-run/remix-webpack-demo#3]
If you save a file, the terminal logs:

```
💿 Rebuilt in 371ms
{ data: '', status: 404, statusText: 'Not Found' }
```

I can't find what is logging it.

**Comment by pcattori** [comment]
Can't reproduce. Though those logs look similar to the thrown 404's in `contacts/$contactId/edit` loader and `conacts/$contactId` index loader.

<img width="959" alt="Screen Shot 2022-11-08 at 11 10 56 AM" src="https://user-images.githubusercontent.com/1477317/200616982-ef35a34d-ba37-4367-bcbb-5eaec448b6a9.png">
